# Generated by Django 3.1 on 2020-08-25 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('atlantis', '0001_initial')]

    initial = True

    dependencies = [
        ('hexmap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('faction_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('weight', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=0)),
                ('purchase_cost', models.IntegerField(help_text='Withdraw cost')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('default_max_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('taxable', models.IntegerField()),
                ('wages', models.IntegerField()),
                ('wage_max', models.IntegerField()),
                ('entertainment_available', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.race')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexmap.region')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('shortcut', models.CharField(max_length=20)),
                ('study_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('is_mage', models.BooleanField(default=False)),
                ('is_quartermaster', models.BooleanField(default=False)),
                ('silver', models.IntegerField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.faction')),
            ],
        ),
        migrations.CreateModel(
            name='UserFaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_points', models.IntegerField(null=True)),
                ('trade_points', models.IntegerField(null=True)),
                ('magic_points', models.IntegerField(null=True)),
                ('default_attitude', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlantis.attitude')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.faction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unclaimed_silver', models.IntegerField()),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.turn')),
                ('user_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userfaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn')),
                ('user_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userfaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unclaimed_silver', models.IntegerField()),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.turn')),
                ('user_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userfaction')),
            ],
        ),
        migrations.CreateModel(
            name='UnitSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.skill')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unitdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('is_mage', models.BooleanField(default=False)),
                ('is_quartermaster', models.BooleanField(default=False)),
                ('silver', models.IntegerField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.faction')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('purchase_cost', models.IntegerField()),
                ('maintenance_cost', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.race')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unitdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UnitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unitdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UnitFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.flag')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unitdetail')),
            ],
        ),
        migrations.AddField(
            model_name='unitdetail',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn'),
        ),
        migrations.AddField(
            model_name='unitdetail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit'),
        ),
        migrations.CreateModel(
            name='TurnEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('event_msg', models.CharField(blank=True, max_length=120)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit')),
                ('user_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn')),
            ],
        ),
        migrations.CreateModel(
            name='TurnError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('error_type', models.CharField(blank=True, max_length=20)),
                ('error_msg', models.CharField(blank=True, max_length=120)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit')),
                ('user_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn')),
            ],
        ),
        migrations.CreateModel(
            name='TimesArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.faction')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.turn')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('description', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.skill')),
            ],
        ),
        migrations.CreateModel(
            name='RegionSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.item')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.regiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='RegionRecruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField()),
                ('price', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.race')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.regiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='RegionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.regiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='RegionNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.regiondetail')),
            ],
        ),
        migrations.AddField(
            model_name='regiondetail',
            name='user_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn'),
        ),
        migrations.CreateModel(
            name='RaceSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.race')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.skilllevel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_time', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.item')),
                ('required_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.skilllevel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.item')),
                ('production_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.productionskill')),
            ],
        ),
        migrations.CreateModel(
            name='FactionAttitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.attitude')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.faction')),
                ('user_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn')),
            ],
        ),
    ]
