# Generated by Django 3.1 on 2020-08-13 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atlantis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_points', models.IntegerField()),
                ('trade_points', models.IntegerField()),
                ('magic_points', models.IntegerField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.faction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='turn',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='turnerror',
            name='turn',
        ),
        migrations.AddField(
            model_name='timesarticle',
            name='faction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='atlantis.faction'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FactionDetail',
        ),
        migrations.AddField(
            model_name='userturn',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.turn'),
        ),
        migrations.AddField(
            model_name='userturn',
            name='user_faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userfaction'),
        ),
        migrations.AddField(
            model_name='turnevent',
            name='user_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn'),
        ),
        migrations.AddField(
            model_name='turnerror',
            name='user_turn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn'),
            preserve_default=False,
        ),
    ]
