# Generated by Django 3.1 on 2020-08-28 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factionattitude',
            name='user_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_attitudes', to='atlantis.userturn'),
        ),
        migrations.AlterField(
            model_name='turnerror',
            name='user_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_errors', to='atlantis.userturn'),
        ),
        migrations.AlterField(
            model_name='turnevent',
            name='user_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_events', to='atlantis.userturn'),
        ),
    ]
