# Generated by Django 3.1 on 2020-08-29 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0002_auto_20200828_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetail',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit'),
        ),
    ]
