# Generated by Django 3.1 on 2020-08-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0002_auto_20200813_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faction',
            options={'ordering': ('faction_id', 'name')},
        ),
    ]
