# Generated by Django 3.1 on 2020-08-13 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0003_auto_20200813_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='user_turn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userturn',
            name='unclaimed_silver',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unitskill',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit'),
        ),
        migrations.CreateModel(
            name='UnitFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.flag')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit')),
            ],
        ),
        migrations.CreateModel(
            name='FactionAttitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.faction')),
                ('user_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn')),
            ],
        ),
        migrations.AddField(
            model_name='userfaction',
            name='default_attitude',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='atlantis.attitude'),
            preserve_default=False,
        ),
    ]
