# Generated by Django 3.1 on 2020-08-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0003_auto_20200829_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit'),
        ),
    ]
