# Generated by Django 3.1 on 2020-09-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0004_auto_20200829_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_details', to='atlantis.unit'),
        ),
    ]
