# Generated by Django 3.1 on 2020-08-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexmap', '0002_auto_20200814_2023'),
        ('atlantis', '0006_auto_20200814_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
                ('taxable', models.IntegerField()),
                ('wages', models.IntegerField()),
                ('wage_max', models.IntegerField()),
                ('entertainment_available', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.race')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexmap.region')),
                ('user_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn')),
            ],
        ),
        migrations.CreateModel(
            name='RegionSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.item')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.regiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='RegionRecruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField()),
                ('price', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.race')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.regiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='RegionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.regiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='RegionNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.regiondetail')),
            ],
        ),
    ]
