# Generated by Django 3.1 on 2020-08-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0007_regiondetail_regionneed_regionproduct_regionrecruit_regionsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AlterField(
            model_name='flag',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unitdetail',
            name='description',
            field=models.TextField(),
        ),
    ]
