# Generated by Django 3.1 on 2020-08-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0008_auto_20200814_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllevel',
            name='study_cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
