# Generated by Django 3.1 on 2020-08-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0009_skilllevel_study_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllevel',
            name='study_cost',
        ),
        migrations.AddField(
            model_name='skill',
            name='study_cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
