# Generated by Django 3.1 on 2020-08-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0010_auto_20200814_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetail',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn'),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.turn')),
                ('user_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userfaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unclaimed_silver', models.IntegerField()),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.turn')),
                ('user_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userfaction')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('is_mage', models.BooleanField(default=False)),
                ('is_quartermaster', models.BooleanField(default=False)),
                ('silver', models.IntegerField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.faction')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn')),
            ],
        ),
    ]
