# Generated by Django 3.1 on 2020-08-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0012_auto_20200817_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='factionattitude',
            name='attitude',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atlantis.attitude'),
            preserve_default=False,
        ),
    ]
