# Generated by Django 3.1 on 2020-08-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0013_factionattitude_attitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='turn_id',
        ),
        migrations.AddField(
            model_name='turn',
            name='turn_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
