# Generated by Django 3.1 on 2020-08-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0014_auto_20200824_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnerror',
            name='error_msg',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='turnerror',
            name='error_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='turnerror',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit'),
        ),
        migrations.AddField(
            model_name='unitdetail',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitorder',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atlantis.unit'),
            preserve_default=False,
        ),
    ]
