# Generated by Django 3.1 on 2020-08-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0017_auto_20200824_2357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turn',
            unique_together={('year', 'month')},
        ),
    ]
