# Generated by Django 3.1 on 2020-08-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0018_auto_20200825_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaction',
            name='default_attitude',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atlantis.attitude'),
        ),
        migrations.AlterField(
            model_name='userfaction',
            name='magic_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userfaction',
            name='trade_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userfaction',
            name='war_points',
            field=models.IntegerField(null=True),
        ),
    ]
