# Generated by Django 3.1 on 2020-08-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hexmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tile',
            new_name='Region',
        ),
    ]
