# Generated by Django 3.1 on 2020-08-25 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='coordinate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hexmap.point'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hexmap.regiontype'),
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('x', 'y', 'z')},
        ),
    ]
