# Generated by Django 3.1 on 2020-08-29 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0004_auto_20200829_0522'),
        ('report_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atlantis.userturn'),
            preserve_default=False,
        ),
    ]
